export const FETCH_CITIES = 'FETCH_CITIES'
export const FILTER_CITIES = 'FILTER_CITIES'
export const ADD_CITY = 'ADD_CITY'

export const FETCH_ITINERARIES = 'FETCH_ITINERARIES'
export const FETCH_ITINERARIES_BY_CITY = 'FETCH_ITINERARIES_BY_CITY'
export const ADD_ITINERARY = 'ADD_ITINERARY'

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES'
export const FETCH_ACTIVITIES_BY_CITY = 'FETCH_ACTIVITIES_BY_CITY'
export const FETCH_ACTIVITIES_BY_ITINERARY = 'FETCH_ACTIVITIES_BY_ITINERARY'
export const ADD_ACTIVITY = 'ADD_ACTIVITY'

export const SET_LOADING = 'SET_LOADING'
export const LOADING_ERROR = 'LOADING_ERROR'
export const POSTING_ERROR = 'POSTING_ERROR'

export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const IS_LOGGED_OUT = 'IS_LOGGED_OUT'
export const LOAD_USER = 'LOAD_USER'
export const UNLOAD_USER = 'UNLOAD_USER'
export const USER_LOADING = 'USER_LOADING'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const SENT_PASSWORD_RESET_LINK_SUCCESS =
  'SENT_PASSWORD_RESET_LINK_SUCCESS'
export const SENT_PASSWORD_RESET_LINK_FAIL = 'SENT_PASSWORD_RESET_LINK_FAIL'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const AUTH_ERROR = 'AUTH_ERROR'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_ERROR = 'UPDATE_ERROR'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
