export const FETCH_CITIES = 'FETCH_CITIES'
export const FETCH_ITINERARIES = 'FETCH_ITINERARIES'
export const FETCH_ITINERARIES_BY_CITY = 'FETCH_ITINERARIES_BY_CITY'

export const SET_LOADING = 'SET_LOADING'
export const LOADING_ERROR = 'LOADING_ERROR'

export const FILTER_CITIES = 'FILTER_CITIES'
export const ADD_CITY = 'ADD_CITY'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const AUTH_ERROR = 'AUTH_ERROR'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
